# Generated by Django 3.0.6 on 2020-05-31 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0004_auto_20200531_2145'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ea',
            name='no',
            field=models.EmailField(max_length=254, primary_key=True, serialize=False),
        ),
    ]
