# Generated by Django 3.0.6 on 2020-06-01 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0006_manufacturer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ea',
            name='phone',
            field=models.BigIntegerField(default=0, null=True),
        ),
    ]
