# Generated by Django 3.0.7 on 2020-06-04 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0008_auto_20200604_1930'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manufacturer',
            name='manufacturer',
            field=models.CharField(default='squirrel', max_length=20),
        ),
    ]
