# Generated by Django 3.0.6 on 2020-05-31 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0002_auto_20200531_2141'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ea',
            name='phone',
            field=models.IntegerField(),
        ),
    ]
