# Generated by Django 3.0.6 on 2020-05-31 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0003_auto_20200531_2144'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ea',
            name='phone',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
