# Generated by Django 3.0.6 on 2020-06-01 13:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0005_auto_20200531_2152'),
    ]

    operations = [
        migrations.CreateModel(
            name='Manufacturer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('partnerName', models.CharField(max_length=20)),
                ('phone', models.IntegerField()),
                ('productName', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='man_name', to='mysite.CI')),
            ],
        ),
    ]
