# Generated by Django 3.0.7 on 2020-06-06 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0010_auto_20200606_1620'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manufacturer',
            name='phone',
            field=models.BigIntegerField(default=0, null=True),
        ),
    ]
