# Generated by Django 3.0.7 on 2020-06-07 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0013_auto_20200607_1351'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manufacturer',
            name='mphone',
            field=models.BigIntegerField(default=0, null=True),
        ),
    ]
